### ISSUE TITLE
%input-available-p for posix.lisp

### ISSUE THREAD

**Issue by jetmonk** [snmsts/cserial-port#11]
I think this works for %input-available-p 

````
(defmethod %input-available-p ((s posix-serial))
  (with-slots (fd) s
    ;; read returns -1 if 0 bytes are read, and no input available
    (not (minusp
	  (read fd (cffi:null-pointer) 0))))) 
````

**Comment by ramenbytes** [comment]
Per the man page on my linux system:  

> In the absence of any errors, or if read() does not check for errors, a read() with a count of 0 returns zero and has no other 
effects.
 
`read()` does return -1 one in case of error though. For checking if there are bytes,`EAGAIN` or `EWOULDBLOCK` are the relevant errors, which would occur if the file descriptor `fd` had the `O_NONBLOCK` flag set. So if the flag is set and there are no bytes to read when we try to read, we'll get a -1. Or if any other error happens. Below is a solution I've been sitting on for a while that uses `ioctrl()` to check the number of bytes available:

```
(defmethod available-bytes ((serial-port posix-serial))
  "Returns the available bytes in SERIAL-PORT's buffer."
  (with-slots (fd) serial-port
    (with-foreign-object (bytes :int 1)
      (nix:ioctl fd nix:fionread bytes)
      (cffi:mem-ref bytes :int))))

;; TODO: Remove redundant methods between this and AVAILABLE-BYTES.
(defmethod %input-available-p ((port posix-serial))
  "Is there pending input from PORT?"
  (plusp (available-bytes port)))
```
It's been a while since I've examined it in depth, but if I recall it fixes the issues with using `read()`. If I have the time to review it again and it checks out, I'll create a pull request.

**Comment by snmsts** [comment]
close it because #15 seems like include @ramenbytes code.
